Module 18 timer
VitaliyVeykshis/TestGuru pull request #18
Opened 2018-05-13 19:49 UTC by VitaliyVeykshis

2018-05-14 17:02 UTC, iBublik requested changes

2018-05-14 17:02 UTC, iBublik commented on app/assets/javascripts/utilities/timer.js
> +  var timer = document.querySelector('.timer')
Рекомендуется писать ; в конце строки, иначе могут вылезти ошибки при сжатии js

2018-05-14 17:02 UTC, iBublik commented on app/assets/javascripts/utilities/timer.js
> +function run_timer(timer) {
В JS принято использовать camelCase нотацию в именовании функций и переменных

2018-05-14 17:02 UTC, iBublik commented on app/assets/javascripts/utilities/timer.js
> +  var test_completed = (timer.dataset.testCompleted == 'true')
Не проще ли возвращать 0 в timeLeft, если тест пройден? Избавимся от доп.параметра

2018-05-14 17:02 UTC, iBublik commented on app/assets/javascripts/utilities/timer.js
> +  if (seconds < 0) seconds = 0
Для какой ситуации нужна эта проверка? Бэк не должен возвращать отрицательное значение, фронт не должен приходить к такому значению

2018-05-14 17:02 UTC, iBublik commented on app/assets/javascripts/utilities/timer.js
> +    function show_time_left() {
Функции, объявленные внутри других функций, лучше записывать в переменные - `var showTimeLeft = function() { ... }`.

2018-05-14 17:02 UTC, iBublik commented on app/assets/javascripts/utilities/timer.js
> +      if (test_completed || seconds <= 0) {
Зачем очередная проверка на отрицательное значение?

2018-05-14 17:02 UTC, iBublik commented on app/assets/javascripts/utilities/timer.js
> +  return date.toISOString().substr(11, 8)
Ты конечно упростил себе жизнь - не надо превращать секнуды в часы и минуты - но код воспринимается как хак. Рекомендую переписать на ручное вычисление, там не так сложно (просто делишь число секунд на число секунд в часе/минуте, если требуется - добавляешь 0 в начало)

2018-05-14 17:02 UTC, iBublik commented on app/controllers/admin/badge_for_test_attempts_controller.rb
> +class Admin::BadgeForTestAttemptsController < ApplicationController
Этот код не относится к данному заданию. Почему он в этой ветке?

2018-05-14 17:02 UTC, iBublik commented on app/models/test_passage.rb
> +    update_columns(updated_at: Time.current, pass: current_result >= percent)
У тебя же этот коллбэк выполняется перед апдейтом. Зачем писать что-то в базу? Просто измени значение поля, а сохранение дальше само произойдет

2018-05-14 17:02 UTC, iBublik commented on app/models/test_passage.rb
> +    update_columns(updated_at: Time.current, time_left: new_time_left)
Зачем time_left хранить в базе? Это виртуальный атрибут, его можно на основе других вычислять в любое время. А так у тебя неактуальное значение будет

2018-05-14 17:02 UTC, iBublik commented on app/views/shared/_timer.html.erb
> +<h1>
А для чего это в shared выносить? Где кроме тестов этот функционал полезен?

2018-05-14 17:02 UTC, iBublik commented on app/views/test_passages/result.html.erb
> +    <%= render 'shared/timer', test_passage: @test_passage %>
А в результатах нам зачем таймер?

2018-05-14 17:02 UTC, iBublik commented on app/helpers/test_passages_helper.rb
> +  def timer(test_passage)
Не вижу смысла этот функционал дублировать и на бэке, и на фронте. На фронте реализовать будет достаточно

2018-05-14 18:46 UTC, VitaliyVeykshis commented on app/controllers/admin/badge_for_test_attempts_controller.rb
> +class Admin::BadgeForTestAttemptsController < ApplicationController
Не знал что коммиты родительской ветки будут отображаться в детской, не знаю как это теперь исправить.

2018-05-14 18:49 UTC, VitaliyVeykshis commented on app/assets/javascripts/utilities/timer.js
> +function run_timer(timer) {
Постоянно забываю об этом, после Rails всё время snake

2018-05-15 13:13 UTC, psylone approved these changes

2018-05-15 13:13 UTC, psylone commented on app/models/test_passage.rb
> +    return test.timer if test.timer.nil?
Лучше просто написать `return`, по умолчанию вернётся `nil`.

2018-05-15 16:40 UTC, merged