Module 3
VitaliyVeykshis/TestGuru pull request #2
Opened 2018-03-16 13:49 UTC by VitaliyVeykshis

2018-03-16 19:16 UTC, iBublik commented on db/migrate/20180316124900_create_tests.rb
> +      t.integer :category_id
Здесь лучше использовать внешний ключ, а не просто числовое поле. Внешний ключ будет контролировать целостность данных - не позволит записать сюда несуществующий id категории, не даст удалить категорию, у которой есть тесты (это поведение настраивается - можно задать каскадное удаление или обнуление поля).

2018-03-16 19:16 UTC, iBublik commented on db/migrate/20180316124900_create_tests.rb
> +    create_table :tests, id: false do |t|
Зачем писать `id: false`, а потом вручную создавать первичный ключ?

2018-03-16 19:16 UTC, iBublik commented on db/migrate/20180316132032_add_categories_title_null_constraint.rb
> +    change_column_null(:categories, :title, false)
Все миграции `change_column_null` я бы в одну схлопнул, т.к. они делают по сути одно и то же

2018-03-16 19:16 UTC, iBublik commented on db/migrate/20180316133715_add_tests_level_default_value.rb
> +    change_column :tests, :level, :integer, default: 0
Есть метод `change_column_default`, он более четко обозначает, что происходит в миграции

2018-03-16 19:16 UTC, iBublik commented on db/migrate/20180316134448_add_answers_correct_default_value.rb
> +    change_column :answers, :correct, :boolean, default: false
Для логических полей рекомендую всегда задавать опцию `null: false`. Тогда в БД будет строга 2 значения (true/false), а не 3 (true/false/null), что сильно упрощает выборки

2018-03-17 10:03 UTC, vkurennov requested changes

2018-03-17 10:03 UTC, vkurennov commented on db/migrate/20180316124900_create_tests.rb
> +    create_table :tests, id: false do |t|
Да, это не имеет смысла. Просто не пиши `id: false`, тогда он будет автоматом создаваться.

2018-03-17 10:03 UTC, vkurennov commented on db/migrate/20180316124900_create_tests.rb
> +      t.integer :category_id
Внешний ключ можно задать через `t.references`

2018-03-17 13:57 UTC, psylone commented on db/schema.rb
> +    t.index ["answer_id"], name: "index_users_on_answer_id"
Какой идентификатор ответа будет храниться в этом атрибуте?

2018-03-17 13:57 UTC, psylone approved these changes

2018-03-18 15:44 UTC, VitaliyVeykshis commented on db/schema.rb
> +    t.index ["answer_id"], name: "index_users_on_answer_id"
В t.index ["answer_id"]?

2018-03-19 12:40 UTC, merged