Module 4
VitaliyVeykshis/TestGuru pull request #3
Opened 2018-03-20 17:34 UTC by VitaliyVeykshis

2018-03-20 18:26 UTC, iBublik requested changes

2018-03-20 18:26 UTC, iBublik commented on app/models/user.rb
> +    Test.joins(questions: [:answers])
При правильной модели данных и описании ассоциаций этот метод был бы намного проще:
```ruby
tests.where(level: level)
```

2018-03-20 18:26 UTC, iBublik commented on app/models/user.rb
> +        .map(&:title)
Здесь как раз экземпляры класса Test нужны, а не просто массив названий

2018-03-20 18:26 UTC, iBublik commented on db/seeds.rb
> +LIST_OF_CATEGORIES = [
А зачем тут константы используются? Они будут в памяти висеть, хотя нужны только для сидирования в БД

2018-03-20 18:26 UTC, iBublik commented on db/seeds.rb
> +  { title: 'Ruby', level: 1, category_id: 2 },
Явно передавать id как числа - плохая затея. Если ты будешь сидировать существующую базу, там могут быть заняты эти id, соответственно связи выстроятся неверно

2018-03-20 18:26 UTC, iBublik commented on db/seeds.rb
> +Category.create(LIST_OF_CATEGORIES)
Лучше использовать `create!` - если что-то не удалось сохранить, выгоднее упасть с ошибкой, иначе есть риск лишиться связей

2018-03-21 00:24 UTC, psylone approved these changes

2018-03-23 03:52 UTC, merged