Module 5, attempt 1
VitaliyVeykshis/TestGuru pull request #4
Opened 2018-03-23 03:57 UTC by VitaliyVeykshis

2018-03-23 14:12 UTC, vkurennov requested changes

2018-03-23 14:12 UTC, vkurennov commented on app/models/author.rb
> +class Author < ApplicationRecord
User - это и есть автор, тут не нужна промежуточная таблица, потому что связь один-ко-многим

2018-03-23 14:12 UTC, vkurennov commented on app/models/test.rb
> +  has_one :author
Нет, тут нужна простая связь belongs_to. Не бывает связей has_one через третью таблицу, это бессмысленно, т.к. третья таблица создается для связей многие-ко-многим.

2018-03-23 14:12 UTC, vkurennov commented on app/models/user.rb
> +  has_many :authors
Что такое "юзер имеет множетсво авторов". Это как? Юзер - это пользователь. Именно он и будет являться автором для тестов. Также юзер может быть и не автором, поэтому **на уровне теста** мы должны отличать юзеров, которые проходят тест (их может быть много) и юзером-автором (он один), т.е. нужно ассоциации у Test  назвать по-разному

2018-03-25 00:17 UTC, psylone approved these changes

2018-03-26 12:22 UTC, merged