Module 9
VitaliyVeykshis/TestGuru pull request #8
Opened 2018-04-04 17:52 UTC by VitaliyVeykshis

2018-04-05 17:08 UTC, iBublik requested changes

2018-04-05 17:08 UTC, iBublik commented on app/helpers/test_passages_helper.rb
> +    if @test_passage.success?(success_minimum)
В хелперах не стоит полагаться на глобальное состояние - не используй инстанс-переменные, передавай переменные как параметры

2018-04-05 17:08 UTC, iBublik commented on app/helpers/test_passages_helper.rb
> +    return 'result-success-color' if @test_passage.success?(success_minimum)
И опять же, не полагайся на инстанс-переменные

2018-04-05 17:08 UTC, iBublik commented on config/routes.rb
> +      post :start
Для краткости можно использовать `post :start, on: :member`

2018-04-05 18:14 UTC, VitaliyVeykshis commented on app/helpers/test_passages_helper.rb
> +      'The test is unsuccessfully passed!'
The test isn't passed - а так?)

2018-04-05 19:38 UTC, VitaliyVeykshis commented on app/models/attempt.rb
> +class Attempt < ApplicationRecord
Хотел сохранить историю ответов на каждый вопрос в каждой попытке.

2018-04-05 20:08 UTC, VitaliyVeykshis commented on app/models/test_passage.rb
> +  before_update :before_save_next_question, on: :update
Теперь понятно, я почемуто понял, что `before_update` срабатывает перед `ActiveRecord update`, а не перед событием в контролере.

2018-04-05 20:15 UTC, VitaliyVeykshis commented on app/models/test_passage.rb
> +    create_attempts(answer_ids) if answer_ids
Способ супер, сам бы никогда не додумался.

2018-04-06 16:28 UTC, psylone approved these changes

2018-04-06 16:28 UTC, psylone commented on app/models/attempt.rb
> +class Attempt < ApplicationRecord
На мой взгляд, адекватный вариант.

2018-04-06 16:41 UTC, iBublik commented on app/helpers/test_passages_helper.rb
> +    if success
Стало лучше, но все-таки я бы сюда саму модель передавал. А тут уже использовал `test_passage.success?`

2018-04-06 16:41 UTC, iBublik commented on app/models/attempt.rb
> +class Attempt < ApplicationRecord
В этом случае все ок, только назвать можно UserAnswer

2018-04-06 16:41 UTC, iBublik commented on app/models/test_passage.rb
> +  before_update :before_save_next_question, on: :update
Ну так и есть, это ведь коллбэк модели. Модель ничего не знает про жизненный цикл контроллера

2018-04-06 23:02 UTC, merged